### ISSUE TITLE
[Error?] res_pjsip/config_system.c:267 in system_create_resolver_and_set_nameservers: There are no local system nameservers configured, resorting to system resolution

### ISSUE THREAD

**Issue by RyTheGuy1** [mlan/docker-asterisk#16]
## Steps to recreate

Create empty project with the structure

Asterisk/
-- Dockerfile
docker-compose.yml

### Docker Compose

```
version: "3.8"

services:
  asterisk:
    build:
      context: ./Asterisk
      dockerfile: Dockerfile
    cap_add:
      - sys_ptrace # Only here to help testing
      - net_admin # Allow NFT, used by AutoBan
      - net_raw # Allow NFT, used by AutoBan
    ports:
      - "${SMS_PORT-8080}:${WEBSMSD_PORT:-80}" # WEBSMSD port mapping
      - "5060:5060/udp" # SIP UDP port
      - "5060:5060" # SIP TCP port
      - "5061:5061" # SIP TLS port
      - "10000-10099:10000-10099/udp" # RTP ports
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4} # Logging
      - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
      - PULSE_SERVER=unix:/run/pulse/socket # Use host audio
      - PULSE_COOKIE=/run/pulse/cookie # Use host audio
      - WEBSMSD_PORT=${WEBSMSD_PORT-80} # WEBSMSD internal port
    volumes:
      - tele-conf:/srv # Persistent storage
      - ./pulse:/run/pulse:rshared # Use host audio
      - /etc/localtime:/etc/localtime:ro # Use host timezone
    dns:
      - 8.8.8.8 # Google's DNS
      - 8.8.4.4 # Google's DNS
      - 1.1.1.1 # Cloudflare's DNS

volumes:
  tele-conf: # Persistent storage
```

### Dockerfile (./Asterisk/Dockerfile)

```
# Use the mlan/asterisk image as the base image
FROM mlan/asterisk:base
```

### Commands
`docker compose build --no-cache`
`docker compose up`
